# Generated by Django 4.0.5 on 2022-06-22 11:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'small'), ('M', 'mediusm'), ('L', 'large'), ('XL', 'extra large')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
